name: youtube_chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      - langchain
      - langchain-core
      - langchain-google-genai
      - langchain-text-splitters
      - google-generativeai
      - langchain-community
      - langchain-huggingface
      - python-dotenv
      - streamlit
      - faiss-cpu
      - youtube-transcript-api
